# Generated by Django 5.2.7 on 2025-11-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActionLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('create_course', 'Creation course'), ('update_course', 'Updation of the course'), ('delete_course', 'Deleting course'), ('login', 'Login'), ('logout', 'Logout'), ('comment', 'Comment'), ('enroll', 'Course Enrollment'), ('unenroll', 'Course Enrollment')], max_length=20),
        ),
    ]
