# Generated by Django 5.2.7 on 2025-11-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActionLog', '0006_alter_actionlog_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
