# Generated by Django 5.2.7 on 2025-11-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActionLog', '0007_alter_actionlog_object_id'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='action_type',
            field=models.CharField(choices=[('create_course', 'Creation course'), ('update_course', 'Updation of the course'), ('delete_course', 'Deleting course'), ('login', 'Login'), ('logout', 'Logout'), ('comment', 'Comment'), ('delete_comment', 'Delete comment'), ('enroll', 'Course Enrollment'), ('unenroll', 'Course Unenrollment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
