# Generated by Django 5.2.7 on 2025-10-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0002_alter_member_managers_alter_member_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('can delete courses', 'Can delete any courses'),), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First name'),
        ),
    ]
