# Generated by Django 5.2.7 on 2025-10-30 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0003_alter_member_options_alter_member_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'permissions': (('can_delete_courses', 'Can delete any courses'),), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
