# Generated by Django 5.2.7 on 2025-10-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0004_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
