# Generated by Django 5.2.7 on 2025-11-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='specialization',
        ),
    ]
