# Generated by Django 5.2.7 on 2025-11-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0002_rename_subject_teacher_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
    ]
