# Generated by Django 5.2.7 on 2025-10-30 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('can_delete_courses', 'Can delete any course')]},
        ),
    ]
