# Generated by Django 5.2.7 on 2025-11-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': [('can_delete_courses', 'Can delete any course'), ('can_edit_courses', 'Can edit any course')]},
        ),
    ]
