# Generated by Django 5.2.7 on 2025-11-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_delete_courses', 'Can delete any comment')]},
        ),
    ]
