# Generated by Django 5.2.7 on 2025-11-09 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_delete_comments', 'Can delete any comment')]},
        ),
    ]
