# Generated by Django 5.2.7 on 2025-11-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0008_course_teacher'),
        ('teachers_app', '0003_remove_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teachers_app.teacher'),
        ),
    ]
